language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28
    - extra-android-m2repository

script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master